### ISSUE TITLE
What should this project be called?

### ISSUE THREAD

**Issue by Nhowka** [Nhowka/Elmish.Bridge#1]
This project was born from the knowledge I got from working on Fable.Remoting. It's one of many amazing projects from @Zaid-Ajaj that I recommend if you don't know about it yet.

Now, it's time to leave the nest; the names are too similar and that will cause confusion.

On one hand, Fable.Remoting is a general use library. You can call functions over the wire and when done on the recommended guidelines is stateless. This project is designed to work on an Elmish environment. It's stateful and changes that state by exchanging messages between client and server (or server-server and client-client, but only the client-server travels through the ~magic channel~ WebSocket.

So. It's a client-server tool for communication with Elmish. Only Elmish. That is an important bit. The Remoting part? Well, I'll be sad to let it go, but we can live with another name. I even brought some options ready, but I'm not a creative person on naming things.

How about `Elmish.Link`? Or maybe `Elmish.Wire`? The project creates a way for messages to go on their way, traveling to change a state on a distant realm. (Or not that far, most action it got was on localhost.)

Enough of story time! Bring me your best names!

**Comment by chmuri** [comment]
Traveling is one thing but on the way needs two directions route so my vote is for Elmish.Route/Routing.

**Comment by MangelMaxime** [comment]
Please do not use `Elmish.Route/Routing` it's really confusing because in JS ecosystem this have another meaning. Where a router is in general responsible for managing the application state based on Url (aka Navigation).

You seems to use a lot the term `Bridge` in the program initialisation perhaps it can lead somewhere.

**Comment by Nhowka** [comment]
@chmuri That also could clash with the [elmish-browser](https://elmish.github.io/browser/routing.html) feature.

@MangelMaxime That is mostly to things that expect the normal Elmish `Program`. It creates a bridge inside the `ClientProgram` to reach it, but it's mostly local and not used in the server context. I don't dislike `Bridge`, but I gave it the same meaning of compatibility layer. 🤔

**Comment by Nhowka** [comment]
It's decided. The next version will be released as `Elmish.Bridge`.
