### ISSUE TITLE
[Suggestion] Let the user handle the message mapping through subscriptions 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Nhowka/Elmish.Bridge#11]
Having the notion of the "top-level" messages is very confusing and to register a specific union case instead of the type of the DU is a bit weird. 

Before talking about implementation details, lets look at things are now, here is my application specific message type on the *client* side: 
```fs
type AppMsg =
  // The messages coming from children
  | PostsMsg of Posts.Types.Msg
  | AdminMsg of Admin.Types.Msg
  // the app messages 
  | LoadBlogInfo
  | BlogInfoLoaded of Result<BlogInfo, string> 
  | BlogInfoLoadFailed of error:string
  | UrlUpdated of Page
  | NavigateTo of Page
  // specialized message coming from server via Elmish.Bridge
  | ServerMsg of RemoteServerMsg
  | DoNothing 
```
where `RemoteServerMsg` is defines as
```fs
// Message from the server, telling the client to reload posts
type RemoteServerMsg = 
    | ReloadPosts 
```
By registering the `ServerMsg` as a mapping in the bridge client, bridge now has the *responsibility* of internally creating an `AppMsg` of case `ServerMsg` and sending it to the [dispatch loop](https://github.com/Nhowka/Elmish.Bridge/blob/master/src/Client/Library.fs#L56) 

My suggestion is as follows: let the user himself do the dispatch and mapping of messages whenever a message is coming from the server using a subscription, it would look this:

```fs
let remoteMsgSub = 
    Bridge.subscribe<RemoteServerMsg> (fun remoteServerMsg dispatch -> 
          // the user creates the AppMsg, not the library
          let appMsg = AppMsg.ServerMsg remoteServerMsg 
          dispatch appMsg 
    )
```
This way, I could have more control and if I wanted, I could remove the `ServerMsg of RemoteServerMsg` from the server entirely and dispatch some other message in my app that is specific to that subscription.

The same would happen on the server, the user subscribes to client messages and maps them himself.

What do you think of this? What challenges do you expect?

**Comment by Nhowka** [comment]
The mapping already can have more logic, the union case is a function and any function that results in the message type that gets dispatched will work.

I made an example with three sockets having the functions on the server doing the minimum possible. The mappings made reusing logic very easy.

https://github.com/Nhowka/MultipleBridges/blob/master/src/Client/Client.fs#L200-L210

The subscription could work and be a nice addition for clients that just need to receive messages but won't need to send anything.

But I don't understand the server side issue, the access to the dispatch doesn't seems like it's needed. The register calls a function that takes that type, transforms it into the type that the dispatch takes and then the user can handle it on the update function.

**Comment by Zaid-Ajaj** [comment]
Thanks for example, I will checkout it out more in-depth to learn what is possible

> The subscription could work and be a nice addition for clients that just need to receive messages but won't need to send anything.

Why can't they do *both* subscribing and sending? 

> The register calls a function that takes that type, transforms it into the type that the dispatch takes and then the user can handle it on the update function.

It is not issue, it is an alternative to this "registering" scenario that (for me at least) makes for a natural way to work with messages, instead of registering the types and dispatching them automatically, let the user decide how to map the shared remote msg into the server-only msg via a subscription to able to dispatch it into server update 

Excuse my ignorance of the different ways of the api can be used, I am just brainstorming here: for now, no need to actually implement anything that might turn out to be a bad idea

**Comment by Nhowka** [comment]
> Why can't they do both subscribing and sending?

For that, there's already the normal flow. I'm thinking that the subscription would only listen and then handle different messages, without registering the different WebSocket output channel on it.

As for the registering, you could do more. The `Bridge.Send` function sends both the input type and the input itself. For it to reach the server, you need to translate that input into something that fits the message on the `update`. The server takes that responsibility because we have a lot of control over it. The ServerHub is like the client in the sense that it accepts any input, that is why we register how to get from that input to what the dispatch expects.

Also, you don't need to have the `ServerMsg` on the server,  just the `RemoteServerMsg`. You can then have a mapping on the client that expects a `RemoteServerMsg` and wraps it into the `ServerMsg`.

You would use it as:

```fsharp
Program.mkProgram init update view
|> Program.withBridgeConfig
    (Bridge.endpoint "..."
    |> Bridge.withMapping ( fun remoteServerMsg -> AppMsg.ServerMsg remoteServerMsg))
|> ...
```

Notice that it's the same as your usage, except by the explicit dispatch. Then you can have a `Dispatch<RemoteServerMsg>` as the client dispatch on the `init` and `update` on the server.

**Comment by Zaid-Ajaj** [comment]
I see, so what I am suggesting is kind of already there, except for the `dispatch` part which is already available from `init` and `update`, did I understand it correctly? 

I will need to play more with this :smile:

**Comment by Nhowka** [comment]
Yes, the server doesn't have a way to know what the client expects so we can leverage that to make it send any kind of messages. Then it's the client job to transform that unknown message into the right message that gets into the dispatch.

I should probably rewrite [that part](https://github.com/Nhowka/Elmish.Bridge/#minimizing-shared-messages) to explain it better. Your documentation is normally amazing, any tips? 😗

**Comment by Zaid-Ajaj** [comment]
> any tips?  

I just follow two rules: "no jargon please" and "there is never too much documentation" , the rest is up to you 😘

**Comment by Zaid-Ajaj** [comment]
No need for this anymore
