### ISSUE TITLE
Websocket connection fails in IE11 / Edge

### ISSUE THREAD

**Issue by 0x53A** [Nhowka/Elmish.Bridge#13]
Apologies for even mentioning IE11 ...

We don't have a strong requirement for IE11, but it would be *really* nice to be able to still support it.

1) I had to polyfill URL with ``url-polyfill``
2) The websocket ctor throws because for some reason there is a hash at the end:

![grafik](https://user-images.githubusercontent.com/4236651/45754073-ec093c80-bc1a-11e8-8e83-b08c96d63d7d.png)

If I set a breakpoint, remove the ``#`` then continue, it works.

---------------------

Do you have any idea where the hash comes from? Maybe it is an issue with ``url-polyfill``, I have no clue.

What do you think about just adding a ``TrimEnd('#')``?

__EDIT:__ Same behavior with Edge (EdgeHTML 16.16299)

**Comment by Nhowka** [comment]
Weird. On Chrome that was solved by giving an empty string to the hash.

https://github.com/Nhowka/Elmish.Bridge/blob/6b639068774f5ce41a78a36e4ba53dba7566f0a6/src/Client/Library.fs#L25

Maybe the polyfill behaves differently, but `TrimEnd('#')` could indeed help. I'll try using it to fix this problem.

**Comment by Nhowka** [comment]
Is version `1.2.1` working?

**Comment by 0x53A** [comment]
Looks good in a quick 5 minute test.

Thank you! 🐧
