### ISSUE TITLE
Integration with Elmish.Streams on the server side

### ISSUE THREAD

**Issue by sheganinans** [Nhowka/Elmish.Bridge#18]
I have a scenario where I am using the `Elmish.Bridge` architecture on the frontend *with* `Elmish.Streams`. However this breaks the isomorphism, since `Elmish.Bridge` on the server side uses `Cmd`s by default, while `Elmish.Streams` does not use `Cmd`s.

You may know, `Elmish.Streams` modifies the `update` function, where instead of generating and returning `Cmd`s there. There is a new function `stream` that is subscribed to `Program.mkSimple` and what would be done by `update` with `Cmd`s, is instead done in `stream`, decoupled from `update`.

What would be a simple way to use `Elmish.Bridge`, modified to use `Elmish.Streams` on the server side?

**Comment by Nhowka** [comment]
As it is now, `Elmish.Streams` hook into the view so it can access both the current model and the dispatch function. The server has no view, so I didn't do a similar concept to support the same features.

The bad news is that changes will need to be made. The good news is that they aren't breaking changes.

I'll see what can be done. Can `Elmish.Streams` work on the server without changes?

**Comment by sheganinans** [comment]
I'm just gonna link in my other issue, since this is fundamentally related: https://github.com/dbrattli/Elmish.Streams/issues/26

How it's done right now in `Elmish.Streams` is that uses websockets explicitly, serialization with `Thoth.Json` hooks into `AspNetCore`'s middlewares: 
https://github.com/dbrattli/Elmish.Streams/blob/master/AspNetCore.Middleware/StreamsMiddleware.fs

The relevant example is `Magic` example, which is essentially the [*Time Files Like An Arrow*](https://elmish-streams.readthedocs.io/en/latest/fable.elmish/demo.html) example, but with toggles for things like local and remote:
https://github.com/dbrattli/Elmish.Streams/blob/master/examples/Magic/src/Client/Utils.fs
https://github.com/dbrattli/Elmish.Streams/blob/master/examples/Magic/src/Shared/Shared.fs
https://github.com/dbrattli/Elmish.Streams/blob/master/examples/Magic/src/Server/Server.fs

I think the simplest way forward would actually be an update of `Elmish.Streams.AspNetCore.Middleware`, maybe a `Elmish.Bridge`-aware version.

**Comment by sheganinans** [comment]
Also, if you don't have the time to do this currently. I'm very motivated right now to get this working. So if you can just get me pointed in the right direction, I'll try to get this working ASAP.

**Comment by Nhowka** [comment]
Probably just reimplement the `setState` will give a way to attach the stream with little change.

**Comment by sheganinans** [comment]
@Nhowka I'm not sure what you mean

**Comment by Nhowka** [comment]
Sorry, there is that feature on [Elmish](https://github.com/elmish/elmish/blob/d3770c3d94aa4542e2debab06f03756ee8d050f5/src/program.fs#L145) that gets called after every update and then is used for rendering the view in the case of `Elmish.React`. As it overrides the `setState` completely, [`Elmish.Streams`](https://github.com/dbrattli/Elmish.Streams/blob/5d001f04dd323b4082b1e52233630c91202b8e94/Fable.Elmish/src/Program.fs#L71) used the view for attaching it to it, but it should be ok with a `setState` based attachment on the `BridgeServer` implementation.

**Comment by sheganinans** [comment]
Closing, since it seems Elmish.Streams is seemingly not actively developed.
