### ISSUE TITLE
ECONNREFUSED errors 

### ISSUE THREAD

**Issue by OnurGumus** [Nhowka/Elmish.Bridge#25]
I am getting 
[HPM] Error occurred while trying to proxy request /socket/init from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /socket from localhost:8080 to http://localhost:8085 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

indefinitely and elmish bridge does not work. 
To reproduce:
1-) Create a new SAFE application with Elmish Bridge
2-) Update all packages via dotnet paket update (or just update Saturn, which in turn updates FSharp.Control.WebSockets and Microsoft.AspNetCore.WebSockets)
3-) Run the app.

**Comment by OnurGumus** [comment]
I found the root cause but it's very weird. Basically the web server wasn't starting. in the build.fsx file
```
    let vsCodeSession = Environment.hasEnvironVar "vsCodeSession"
    //don't remove this comment otherwise it doesn't work, LITERALLY doesn't work! :/
    let safeClientOnly = Environment.hasEnvironVar "safeClientOnly"
````
If you remove the comment it just doesn't work. Weird but true. Some bug with fake I guess.

**Comment by Zaid-Ajaj** [comment]
@OnurGumus you might need to clear some cached directories like `.fake`, `paket-files`, `bin` and `obj` to reset the run  process
