### ISSUE TITLE
Fable.Elmish 3.1 breaks Elmish.Bridge

### ISSUE THREAD

**Issue by OnurGumus** [Nhowka/Elmish.Bridge#27]
When I try to use elmish.bridge with 3.1, it fails with "initialization error", all packages are at the latest stable version. Using WSL on Win 10 x64
Related issue: elmish/elmish#206

**Comment by Nhowka** [comment]
I tried it with BridgeChat and couldn't reproduce the error. Are you sure it's coming from Bridge?

**Comment by OnurGumus** [comment]
Ok proved to be an issue on my part but also the way elmish changed
