### ISSUE TITLE
Fable.SimpleJson stringify error in Bridge.Sender

### ISSUE THREAD

**Issue by pkese** [Nhowka/Elmish.Bridge#35]
`Cmd.bridgeSend` appears to trigger a runtime error:

![image](https://user-images.githubusercontent.com/278492/111235959-0b1d9500-85f2-11eb-93d3-07dd891c3d50.png)

I have published a repo that makes bug reproducible at: https://github.com/pkese/Elmish.Bridge.Test

To run:
```
  Shell tab ./Elmish.Bridge.Test
 -------------------------------------- --------------------------------------
  > cd server                            > cd client
  > dotnet restore                       > npm install
  > dotnet run                           > ./run.sh
```

While processing `Welcome` message it fails to serialize `Cmd.bridgeSend UpstreamMsg.GetState`

**Comment by pkese** [comment]
_In case you're wondering what the hell I was doing in server/Program.fs:  
(the bug not related to that)._

_I'm trying to fiddle with some hardware on a Raspberry PI_  
_and there's some impedance mismatch with Elmish.Bridge, because_
- _on Raspberry, I need only one single global elmish app (in this case it is Counter, but on real Raspberry, it's elmish app controlling sensors & relays which are HW bound and can't be scaled for each client)._
- _Elmish.Bridge on the other hand creates a separate elmish state for each connected client._

_So I somehow hacked a way to get `dispatch` from Global app and then I proxy client messages to global app using this stolen `dispatch`.  
In the other direction I'm using Hub to dispatch state to all connected clients._

... I'm not sure how to better express that.  
Inside the Bridge Hub, there probably is some similar "global singleton" state & logic, but unfortunately I can't plug into that.

**Comment by Zaid-Ajaj** [comment]
Fable 3 should use Json.serialize instead of JSON.stringify

**Comment by Nhowka** [comment]
Thanks, @Zaid-Ajaj! I'll replace it with `serialize` and upload a new package in a moment

**Comment by Nhowka** [comment]
The [rc-3](https://www.nuget.org/packages/Elmish.Bridge.Client/5.0.0-rc-3) version should be listed in a moment. Can you check if that fixes the issue, @pkese?

**Comment by Zaid-Ajaj** [comment]
@Nhowka please also add an Exclude="*.fs.js" to your Fable client package. See tempting client for reference

**Comment by pkese** [comment]
@Nhowka yes, now it works like a charm.  
Thanks for the update.

**Comment by Nhowka** [comment]
> @Nhowka please also add an Exclude="*.fs.js" to your Fable client package. See tempting client for reference

@Zaid-Ajaj, I saw that in Feliz there is also an inclusion for `*.js`, should I need to add it? Should I need to exclude the `*.fs.js` files if I don't have an include for `*.js`?

**Comment by pkese** [comment]
... oh and I've noticed that I was testing with an old Elmish.Bridge.Client when I found that bug (apparently I only upgraded the server side Elmish.Bridge.Giraffe to 5.0.0-rc2 but not the client).  
So now it works with 5.0.0-rc3, but I never really tested the client with 5.0.0-rc2.

I hope it wasn't a bogus bug report all along.

**Comment by Zaid-Ajaj** [comment]
@Nhowka Feliz only includes .js files because it uses a couple of them for interop. The idea behind excluding .fs.js file is because users get weird issues where the source files of your package aren't being compiled

**Comment by Nhowka** [comment]
@Zaid-Ajaj I added for the next version, it's harmless and it could prevent disaster. 😗 

@pkese I was testing with BridgeChat and it was working, but I probably should be using `serialize` anyway! 😅

**Comment by Zaid-Ajaj** [comment]
@pkese just in case, try `dotnet fable clean --yes` before restarting the application to delete build artifacts
