### ISSUE TITLE
BroadcastServer doesn't work

### ISSUE THREAD

**Issue by Alkasai** [Nhowka/Elmish.Bridge#43]
I tried broadcasting message using `BroadcastServer`, but it is not being received on the server.
Looking at the code [here](https://github.com/Nhowka/Elmish.Bridge/blob/4139a59c030261008e9a63a7f64aa74b8f2a846b/src/Server/Library.fs#L313)
```
        default sh.BroadcastServer(msg: 'inner) =
        sh.SendClientIf (fun _ -> true) msg
```

shouldn't that be `SendServerIf` instead?
```
        default sh.BroadcastServer(msg: 'inner) =
        sh.SendServerIf (fun _ -> true) msg
```

I'm using `Elmish.Bridge.Server` version `6.0.0`

**Comment by Nhowka** [comment]
Yes, my mistake! I'll upload a new version soon with the fix

**Comment by Alkasai** [comment]
Awesome! Thank you!

**Comment by Alkasai** [comment]
There you go :)
https://github.com/Nhowka/Elmish.Bridge/pull/44

**Comment by Nhowka** [comment]
Aww, thanks! Already uploaded the nuget files with the mentioned fix
