### ISSUE TITLE
Update to Elmish v4

### ISSUE THREAD

**Issue by OnurGumus** [Nhowka/Elmish.Bridge#48]
Elmish v4 has some changes with subscription, my fix locally looks like below

```fsharp
[<RequireQualifiedAccess>]
module Program =
    /// Apply the `Bridge` to be used with the program.
    /// Preferably use it before any other operation that can change the type of the message passed to the `Program`.
    let inline withBridge endpoint (program : Program<_, _, _, _>) =
        program |> Program.withSubscription (fun _ -> [["withBridge"],Bridge.endpoint(endpoint).Attach])

    /// Apply the `Bridge` to be used with the program.
    /// Preferably use it before any other operation that can change the type of the message passed to the `Program`.
    let inline withBridgeConfig (config:BridgeConfig<_,_>) (program : Program<_, _, _, _>) =
        program |> Program.withSubscription (fun _ -> ( [ ["withBridgeConfig"], config.Attach ]))
```

And return disposable from attach

<img width="884" alt="image" src="https://user-images.githubusercontent.com/4114592/209466172-1b823bf4-5b58-4f27-acee-c7a9bb769d6d.png">

**Comment by OnurGumus** [comment]
Serverside is a bit more tricky though.

**Comment by Nhowka** [comment]
@OnurGumus Could you test the branch [elmish-v4](https://github.com/Nhowka/Elmish.Bridge/tree/elmish-v4) and confirm if that it is working? If there are no issues, I can publish a new NuGet version asap.

**Comment by OnurGumus** [comment]
@Nhowka Tested and works good. Note I didn't test the dotnet client and my scenario is somewhat basic at the moment :) So please publish.

**Comment by Nhowka** [comment]
It should be available as soon as nuget finishes processing it. Thank you for the initial testing!
