### ISSUE TITLE
Getting all the messages into the Shared isn't the best option for a big project

### ISSUE THREAD

**Issue by cotyar** [Nhowka/Elmish.Bridge#5]
(More like a discussion topic.)

Getting all the messages into the Shared isn't the best option for a big project. 
The reason is too tight dependency on ClientMsg-s server side which for a UI reach project turns in necessity of including all pure UI messages (e.g. button pressed on say login screen) into the Shared project and making them visible on server. With corresponding models.
All this creates a bit of mess in the separation of concerns. Especially as UIs tend to grow in size quite fast comparing to the communication layer.
Really server shouldn't know about (and shouldn't depend on) pure UI things and on the UI side extracting server communication into a separate layer would be a bit cleaner as well.

So the proposal is to have in Shared something like this:

module WsBridge =
    // Messages processed on the server
    type ServerMsg =
        | Closed 
        | ConnectUser of AuthToken
        | DisconnectUser
    //Messages processed on the client
    type BridgeMsg =
        | BS of BridgeServerMsg
        | BC of BridgeClientMsg
    and BridgeServerMsg =
        | ConnectUserOnServer       of AuthToken
        | DisconnectUserOnServer
    and BridgeClientMsg =
        | ErrorResponse             of ServerError * Request: ServerMsg
        | ConnectionLost
        | ServerConnected
        | UserConnected             of AuthToken 

And in Client remapped BridgeMsg to ClientMsg with a separate pair of init()/update() functions (where AppMsg is visible in the Client project only and holds whole complex UI logic): 
type ClientMsg = 
    | BridgeMsg of WsBridge.BridgeMsg
    | AppMsg    of AppMsg

type BridgedMsg = Msg<WsBridge.ServerMsg, ClientMsg>

I've seen your discussion with @Zaid-Ajaj and do support you in emphasising that Remoting and Bridge can coexist within the same project. For at least a couple of reasons:
- rpc flow is simply easier for the client-started communication
- it maybe difficult to migrate existing rpc into the message-passing workflow overnight.
Literally the approaches pursue different use cases and should easily coexist.

I've got a working implementation but it's based on previous version of Remoting (the CE one - should be an issue so) and I'm not fully happy with one small arch decision (clearly need your advise on this one).
Will clean up the code and share this bit in a gist within the next couple of days. 

Cheers
Yuriy

**Comment by Nhowka** [comment]
I'll need to see more code before being convinced. The models don't need to be shared, just the messages. The server process only server messages and don't need to send UI related messages for the client, nor the client needs to send all kind of server messages back.

What I mean is that I don't see it as a _dependency_. You will just have a choice to send that message or not. Having an extra layer of `update` functions to separate it more goes against what I want to achieve with this project, that was extending the Elmish messaging to a two-way communication as seamless as possible.

**Comment by cotyar** [comment]
Sure
Imagine you have a registration/login flow on the client side. (4 forms with 3-4 fields, with field validations and form validation)  + 4 page wizard full of similar forms + nav menu + context menu. 
msgs to the server may require authtoken and resend on fail (so need buffering them)

**Comment by Nhowka** [comment]
I have an idea that may work. It will be a breaking change, but probably will be for the best.

I'll focus on that tomorrow.

**Comment by cotyar** [comment]
I'll share what I've done tomorrow (sorry, cannot do it today).
It's not a breaking one but slightly not ideal in one place.

Thank you Diego

**Comment by Nhowka** [comment]
Should be better now with #6
