### ISSUE TITLE
Client's bridge removes the program's other subscriptions

### ISSUE THREAD

**Issue by lukaszkrzywizna** [Nhowka/Elmish.Bridge#51]
According to Elmish release notes

https://github.com/elmish/elmish/blob/v4.x/RELEASE_NOTES.md
> Breaking: withSubscription replaces existing subscription, use mapSubscription to add/accumulate the subscribers

when Elmish.Bridge is registered, any previously added subscription will be removed. I suggest migrating clients to `mapSubscription` and aggregating all previous subs.

**Comment by Nhowka** [comment]
Thanks! Sorry about the delay, I was replacing my computer. I will upload an updated version as soon as possible!
