### ISSUE TITLE
Update to Fable.Browser.Url 1.3.2

### ISSUE THREAD

**Issue by MangelMaxime** [Nhowka/Elmish.Bridge#53]
Hello @Nhowka.

in one of the latest version of Fable.Browser.Url we fixed the `URL.Create`.

The problem is that even if the new signature is in theory compatible with the previous one F#/.NET is not able to pick it when used in already published packages.

![image](https://user-images.githubusercontent.com/4760796/216111210-b7f6df41-e83c-428b-970b-89bf759ee660.png)

https://github.com/fable-compiler/fable-browser/issues/116

Can you please update `Elmish.Bridge.Clilent` to `Fable.Browser.Url` version 1.3.2? In theory, you just need to update the dependency and have nothing to change in your code.

**Comment by Nhowka** [comment]
Version 7.0.2 should contain the fix. Thanks!

**Comment by lukaszkrzywizna** [comment]
Hi, @Nhowka

Thank you for the update!
Is there any chance to release that fix for `6.x` version? Our project still uses `Fable.v3` along with `Fable.Elmish 3`. I would much appreciate it. Thanks! :)

**Comment by Nhowka** [comment]
@lukaszkrzywizna I just uploaded version 6.0.2 with only the dependency change!
