### ISSUE TITLE
Socket timeout

### ISSUE THREAD

**Issue by vasily-kirichenko** [Nhowka/Elmish.Bridge#8]
![image](https://user-images.githubusercontent.com/873919/43217997-d3fd59c8-904b-11e8-94c3-a19d93b19bde.png)

What may be the problem?

**Comment by vasily-kirichenko** [comment]
My hello world project is here https://github.com/vasily-kirichenko/safe4

**Comment by Nhowka** [comment]
Sorry for the delay. Looks like the webpack dev don't redirect websocket connections by default. That is the config I'm using on my project:
https://github.com/Nhowka/TestRemoting/blob/master/src/Client/webpack.config.js#L39-L47

I'll add that information to the README.

**Comment by Nhowka** [comment]
Information added. https://github.com/Nhowka/Elmish.Bridge#webpack-caveat

Let me know if that is not enough.

**Comment by vasily-kirichenko** [comment]
@Nhowka Thank you! Everything works now. What an exciting library!
