### ISSUE TITLE
Provide an example of Bridge.withSubscription usage

### ISSUE THREAD

**Issue by vasily-kirichenko** [Nhowka/Elmish.Bridge#9]
Could you please provide an example of `Bridge.withSubscription`?
As I understand, it accepts a function `'model -> Cmd<'a>`, like this:
```fsharp
Bridge.withSubscription (fun model -> Cmd.none)
```
But I'm puzzled how to emit command via this API.

What I need is to emit messages to server Bridge, from other asynchronous things, like MBP or Akka actors. Is `withSubscription` is the right tool for this?

**Comment by Nhowka** [comment]
I added it mostly to replicate the Elmish features, but probably the `ServerHub` features could be better on this case. But the API is the same, it just enables you to get access to the dispatch function outside it.

**Comment by Nhowka** [comment]
The same guide works: https://elmish.github.io/elmish/subscriptions.html

**Comment by vasily-kirichenko** [comment]
Thanks, `ServerHub` works for my task.
